export const ORDER_STATUS = {
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED',
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  PACKED: 'PACKED',
  SHIPPED: 'SHIPPED',
  COMPLETED: 'COMPLETED',
} as const;
