export const ORDER_STATUS = {
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED',
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  PACKED: 'PACKED',
  SHIPPED: 'SHIPPED',
  COMPLETED: 'COMPLETED',
  READY_FOR_PICKUP: "READY_FOR_PICKUP",
  IN_TRANSIT: "IN_TRANSIT",
} as const;
